import { SEED_WORDS, type SeedWord } from '@/lib/seed-words';

export interface WordPack {
  id: string;
  name: string;
  description: string;
  emoji: string;
  words: SeedWord[];
}

const FOOD_WORDS: SeedWord[] = [
  { es: 'desayuno', ru: 'завтрак', pos: 'noun' },
  { es: 'almuerzo', ru: 'обед', pos: 'noun' },
  { es: 'cena', ru: 'ужин', pos: 'noun' },
  { es: 'restaurante', ru: 'ресторан', pos: 'noun' },
  { es: 'camarero', ru: 'официант', pos: 'noun' },
  { es: 'menú', ru: 'меню', pos: 'noun' },
  { es: 'cuenta', ru: 'счёт', pos: 'noun' },
  { es: 'propina', ru: 'чаевые', pos: 'noun' },
  { es: 'arroz', ru: 'рис', pos: 'noun' },
  { es: 'huevo', ru: 'яйцо', pos: 'noun' },
  { es: 'queso', ru: 'сыр', pos: 'noun' },
  { es: 'pollo', ru: 'курица', pos: 'noun' },
  { es: 'sopa', ru: 'суп', pos: 'noun' },
  { es: 'ensalada', ru: 'салат', pos: 'noun' },
  { es: 'postre', ru: 'десерт', pos: 'noun' },
  { es: 'helado', ru: 'мороженое', pos: 'noun' },
  { es: 'pastel', ru: 'торт, пирог', pos: 'noun' },
  { es: 'azúcar', ru: 'сахар', pos: 'noun' },
  { es: 'sal', ru: 'соль', pos: 'noun' },
  { es: 'pimienta', ru: 'перец', pos: 'noun' },
  { es: 'aceite', ru: 'масло (растительное)', pos: 'noun' },
  { es: 'mantequilla', ru: 'сливочное масло', pos: 'noun' },
  { es: 'cuchara', ru: 'ложка', pos: 'noun' },
  { es: 'tenedor', ru: 'вилка', pos: 'noun' },
  { es: 'cuchillo', ru: 'нож', pos: 'noun' },
  { es: 'plato', ru: 'тарелка, блюдо', pos: 'noun' },
  { es: 'vaso', ru: 'стакан', pos: 'noun' },
  { es: 'taza', ru: 'чашка', pos: 'noun' },
  { es: 'botella', ru: 'бутылка', pos: 'noun' },
  { es: 'jugo', ru: 'сок', pos: 'noun' },
  { es: 'cerveza', ru: 'пиво', pos: 'noun' },
  { es: 'naranja', ru: 'апельсин', pos: 'noun' },
  { es: 'plátano', ru: 'банан', pos: 'noun' },
  { es: 'uva', ru: 'виноград', pos: 'noun' },
  { es: 'fresa', ru: 'клубника', pos: 'noun' },
  { es: 'tomate', ru: 'помидор', pos: 'noun' },
  { es: 'patata', ru: 'картофель', pos: 'noun' },
  { es: 'cebolla', ru: 'лук', pos: 'noun' },
  { es: 'ajo', ru: 'чеснок', pos: 'noun' },
  { es: 'pedir', ru: 'заказывать, просить', pos: 'verb' },
  { es: 'probar', ru: 'пробовать', pos: 'verb' },
  { es: 'desayunar', ru: 'завтракать', pos: 'verb' },
  { es: 'sabroso', ru: 'вкусный', pos: 'adj' },
  { es: 'dulce', ru: 'сладкий', pos: 'adj' },
  { es: 'salado', ru: 'солёный', pos: 'adj' },
  { es: 'picante', ru: 'острый', pos: 'adj' },
  { es: 'fresco', ru: 'свежий', pos: 'adj' },
  { es: 'tengo hambre', ru: 'я голоден', pos: 'phrase' },
  { es: 'tengo sed', ru: 'я хочу пить', pos: 'phrase' },
  { es: 'la cuenta, por favor', ru: 'счёт, пожалуйста', pos: 'phrase' },
];

const TRAVEL_WORDS: SeedWord[] = [
  { es: 'viaje', ru: 'путешествие', pos: 'noun' },
  { es: 'aeropuerto', ru: 'аэропорт', pos: 'noun' },
  { es: 'vuelo', ru: 'рейс, полёт', pos: 'noun' },
  { es: 'estación', ru: 'вокзал, станция', pos: 'noun' },
  { es: 'billete', ru: 'билет', pos: 'noun' },
  { es: 'pasaporte', ru: 'паспорт', pos: 'noun' },
  { es: 'maleta', ru: 'чемодан', pos: 'noun' },
  { es: 'equipaje', ru: 'багаж', pos: 'noun' },
  { es: 'hotel', ru: 'отель', pos: 'noun' },
  { es: 'reserva', ru: 'бронь', pos: 'noun' },
  { es: 'llave', ru: 'ключ', pos: 'noun' },
  { es: 'mapa', ru: 'карта (географическая)', pos: 'noun' },
  { es: 'turista', ru: 'турист', pos: 'noun' },
  { es: 'guía', ru: 'гид; путеводитель', pos: 'noun' },
  { es: 'museo', ru: 'музей', pos: 'noun' },
  { es: 'iglesia', ru: 'церковь', pos: 'noun' },
  { es: 'plaza', ru: 'площадь', pos: 'noun' },
  { es: 'puente', ru: 'мост', pos: 'noun' },
  { es: 'centro', ru: 'центр', pos: 'noun' },
  { es: 'taxi', ru: 'такси', pos: 'noun' },
  { es: 'metro', ru: 'метро', pos: 'noun' },
  { es: 'autobús', ru: 'автобус', pos: 'noun' },
  { es: 'parada', ru: 'остановка', pos: 'noun' },
  { es: 'salida', ru: 'выход; отправление', pos: 'noun' },
  { es: 'entrada', ru: 'вход; билет на вход', pos: 'noun' },
  { es: 'frontera', ru: 'граница', pos: 'noun' },
  { es: 'aduana', ru: 'таможня', pos: 'noun' },
  { es: 'cámara', ru: 'фотоаппарат', pos: 'noun' },
  { es: 'foto', ru: 'фотография', pos: 'noun' },
  { es: 'recuerdo', ru: 'сувенир; воспоминание', pos: 'noun' },
  { es: 'norte', ru: 'север', pos: 'noun' },
  { es: 'sur', ru: 'юг', pos: 'noun' },
  { es: 'este', ru: 'восток', pos: 'noun' },
  { es: 'oeste', ru: 'запад', pos: 'noun' },
  { es: 'derecha', ru: 'право, направо', pos: 'other' },
  { es: 'izquierda', ru: 'лево, налево', pos: 'other' },
  { es: 'recto', ru: 'прямо', pos: 'adv' },
  { es: 'cerca', ru: 'близко', pos: 'adv' },
  { es: 'lejos', ru: 'далеко', pos: 'adv' },
  { es: 'reservar', ru: 'бронировать', pos: 'verb' },
  { es: 'visitar', ru: 'посещать', pos: 'verb' },
  { es: 'perderse', ru: 'заблудиться', pos: 'verb' },
  { es: '¿dónde está...?', ru: 'где находится...?', pos: 'phrase' },
  { es: '¿cuánto cuesta?', ru: 'сколько стоит?', pos: 'phrase' },
  { es: 'no entiendo', ru: 'я не понимаю', pos: 'phrase' },
  { es: '¿habla usted inglés?', ru: 'вы говорите по-английски?', pos: 'phrase' },
];

const NUMBERS_TIME_WORDS: SeedWord[] = [
  { es: 'cero', ru: 'ноль', pos: 'other' },
  { es: 'uno', ru: 'один', pos: 'other' },
  { es: 'dos', ru: 'два', pos: 'other' },
  { es: 'tres', ru: 'три', pos: 'other' },
  { es: 'cuatro', ru: 'четыре', pos: 'other' },
  { es: 'cinco', ru: 'пять', pos: 'other' },
  { es: 'seis', ru: 'шесть', pos: 'other' },
  { es: 'siete', ru: 'семь', pos: 'other' },
  { es: 'ocho', ru: 'восемь', pos: 'other' },
  { es: 'nueve', ru: 'девять', pos: 'other' },
  { es: 'diez', ru: 'десять', pos: 'other' },
  { es: 'veinte', ru: 'двадцать', pos: 'other' },
  { es: 'treinta', ru: 'тридцать', pos: 'other' },
  { es: 'cuarenta', ru: 'сорок', pos: 'other' },
  { es: 'cincuenta', ru: 'пятьдесят', pos: 'other' },
  { es: 'cien', ru: 'сто', pos: 'other' },
  { es: 'mil', ru: 'тысяча', pos: 'other' },
  { es: 'primero', ru: 'первый', pos: 'adj' },
  { es: 'último', ru: 'последний', pos: 'adj' },
  { es: 'lunes', ru: 'понедельник', pos: 'noun' },
  { es: 'martes', ru: 'вторник', pos: 'noun' },
  { es: 'miércoles', ru: 'среда', pos: 'noun' },
  { es: 'jueves', ru: 'четверг', pos: 'noun' },
  { es: 'viernes', ru: 'пятница', pos: 'noun' },
  { es: 'sábado', ru: 'суббота', pos: 'noun' },
  { es: 'domingo', ru: 'воскресенье', pos: 'noun' },
  { es: 'fin de semana', ru: 'выходные', pos: 'phrase' },
  { es: 'primavera', ru: 'весна', pos: 'noun' },
  { es: 'verano', ru: 'лето', pos: 'noun' },
  { es: 'otoño', ru: 'осень', pos: 'noun' },
  { es: 'invierno', ru: 'зима', pos: 'noun' },
  { es: 'minuto', ru: 'минута', pos: 'noun' },
  { es: 'segundo', ru: 'секунда; второй', pos: 'noun' },
  { es: 'reloj', ru: 'часы', pos: 'noun' },
  { es: 'fecha', ru: 'дата', pos: 'noun' },
  { es: 'cumpleaños', ru: 'день рождения', pos: 'noun' },
  { es: 'temprano', ru: 'рано', pos: 'adv' },
  { es: 'tarde', ru: 'поздно; вечер', pos: 'adv' },
  { es: '¿qué hora es?', ru: 'который час?', pos: 'phrase' },
];

export const WORD_PACKS: WordPack[] = [
  {
    id: 'base200',
    name: 'Базовый словарь',
    description: '200 самых нужных слов для начала',
    emoji: '📗',
    words: SEED_WORDS,
  },
  {
    id: 'food',
    name: 'Еда и ресторан',
    description: 'Продукты, посуда и фразы в кафе',
    emoji: '🍽️',
    words: FOOD_WORDS,
  },
  {
    id: 'travel',
    name: 'Путешествия',
    description: 'Транспорт, отель и фразы туриста',
    emoji: '✈️',
    words: TRAVEL_WORDS,
  },
  {
    id: 'numbers',
    name: 'Числа и время',
    description: 'Числа, дни недели и времена года',
    emoji: '🕐',
    words: NUMBERS_TIME_WORDS,
  },
];
