import { SEED_WORDS, type SeedWord } from '@/lib/seed-words';

export interface WordPack {
  id: string;
  name: string;
  description: string;
  emoji: string;
  // Код изучаемого языка — см. src/lib/languages.ts
  language: string;
  words: SeedWord[];
}

const ENGLISH_BASE_WORDS: SeedWord[] = [
  // Приветствия и фразы
  { es: 'hello', ru: 'привет', pos: 'phrase' },
  { es: 'goodbye', ru: 'до свидания', pos: 'phrase' },
  { es: 'good morning', ru: 'доброе утро', pos: 'phrase' },
  { es: 'good night', ru: 'доброй ночи', pos: 'phrase' },
  { es: 'please', ru: 'пожалуйста', pos: 'phrase' },
  { es: 'thank you', ru: 'спасибо', pos: 'phrase' },
  { es: 'excuse me', ru: 'извините', pos: 'phrase' },
  { es: 'how are you?', ru: 'как дела?', pos: 'phrase' },
  { es: 'nice to meet you', ru: 'приятно познакомиться', pos: 'phrase' },
  { es: 'see you later', ru: 'до встречи', pos: 'phrase' },
  // Базовые слова
  { es: 'yes', ru: 'да', pos: 'other' },
  { es: 'no', ru: 'нет', pos: 'other' },
  { es: 'I', ru: 'я', pos: 'other' },
  { es: 'you', ru: 'ты, вы', pos: 'other' },
  { es: 'he', ru: 'он', pos: 'other' },
  { es: 'she', ru: 'она', pos: 'other' },
  { es: 'we', ru: 'мы', pos: 'other' },
  { es: 'they', ru: 'они', pos: 'other' },
  { es: 'this', ru: 'это, этот', pos: 'other' },
  { es: 'what', ru: 'что', pos: 'other' },
  { es: 'who', ru: 'кто', pos: 'other' },
  { es: 'where', ru: 'где', pos: 'other' },
  { es: 'when', ru: 'когда', pos: 'other' },
  { es: 'why', ru: 'почему', pos: 'other' },
  { es: 'how', ru: 'как', pos: 'other' },
  { es: 'and', ru: 'и', pos: 'other' },
  { es: 'or', ru: 'или', pos: 'other' },
  { es: 'but', ru: 'но', pos: 'other' },
  { es: 'because', ru: 'потому что', pos: 'other' },
  { es: 'with', ru: 'с (кем-то, чем-то)', pos: 'other' },
  { es: 'without', ru: 'без', pos: 'other' },
  { es: 'for', ru: 'для', pos: 'other' },
  // Глаголы
  { es: 'be', ru: 'быть', pos: 'verb' },
  { es: 'have', ru: 'иметь', pos: 'verb' },
  { es: 'do', ru: 'делать', pos: 'verb' },
  { es: 'go', ru: 'идти, ехать', pos: 'verb' },
  { es: 'come', ru: 'приходить', pos: 'verb' },
  { es: 'see', ru: 'видеть', pos: 'verb' },
  { es: 'give', ru: 'давать', pos: 'verb' },
  { es: 'take', ru: 'брать', pos: 'verb' },
  { es: 'know', ru: 'знать', pos: 'verb' },
  { es: 'want', ru: 'хотеть', pos: 'verb' },
  { es: 'can', ru: 'мочь', pos: 'verb' },
  { es: 'say', ru: 'сказать', pos: 'verb' },
  { es: 'speak', ru: 'говорить', pos: 'verb' },
  { es: 'eat', ru: 'есть, кушать', pos: 'verb' },
  { es: 'drink', ru: 'пить', pos: 'verb' },
  { es: 'live', ru: 'жить', pos: 'verb' },
  { es: 'work', ru: 'работать', pos: 'verb' },
  { es: 'study', ru: 'учиться', pos: 'verb' },
  { es: 'learn', ru: 'изучать', pos: 'verb' },
  { es: 'read', ru: 'читать', pos: 'verb' },
  { es: 'write', ru: 'писать', pos: 'verb' },
  { es: 'listen', ru: 'слушать', pos: 'verb' },
  { es: 'look', ru: 'смотреть', pos: 'verb' },
  { es: 'find', ru: 'находить', pos: 'verb' },
  { es: 'buy', ru: 'покупать', pos: 'verb' },
  { es: 'sell', ru: 'продавать', pos: 'verb' },
  { es: 'pay', ru: 'платить', pos: 'verb' },
  { es: 'open', ru: 'открывать', pos: 'verb' },
  { es: 'close', ru: 'закрывать', pos: 'verb' },
  { es: 'start', ru: 'начинать', pos: 'verb' },
  { es: 'finish', ru: 'заканчивать', pos: 'verb' },
  { es: 'understand', ru: 'понимать', pos: 'verb' },
  { es: 'think', ru: 'думать', pos: 'verb' },
  { es: 'believe', ru: 'верить', pos: 'verb' },
  { es: 'remember', ru: 'помнить', pos: 'verb' },
  { es: 'forget', ru: 'забывать', pos: 'verb' },
  { es: 'sleep', ru: 'спать', pos: 'verb' },
  { es: 'play', ru: 'играть', pos: 'verb' },
  { es: 'help', ru: 'помогать', pos: 'verb' },
  { es: 'need', ru: 'нуждаться', pos: 'verb' },
  { es: 'call', ru: 'звать, звонить', pos: 'verb' },
  { es: 'wait', ru: 'ждать', pos: 'verb' },
  { es: 'love', ru: 'любить', pos: 'verb' },
  { es: 'like', ru: 'нравиться', pos: 'verb' },
  { es: 'use', ru: 'использовать', pos: 'verb' },
  { es: 'travel', ru: 'путешествовать', pos: 'verb' },
  { es: 'bring', ru: 'приносить', pos: 'verb' },
  { es: 'put', ru: 'класть, ставить', pos: 'verb' },
  // Существительные
  { es: 'house', ru: 'дом', pos: 'noun' },
  { es: 'time', ru: 'время', pos: 'noun' },
  { es: 'day', ru: 'день', pos: 'noun' },
  { es: 'night', ru: 'ночь', pos: 'noun' },
  { es: 'week', ru: 'неделя', pos: 'noun' },
  { es: 'year', ru: 'год', pos: 'noun' },
  { es: 'man', ru: 'мужчина, человек', pos: 'noun' },
  { es: 'woman', ru: 'женщина', pos: 'noun' },
  { es: 'child', ru: 'ребёнок', pos: 'noun' },
  { es: 'friend', ru: 'друг', pos: 'noun' },
  { es: 'family', ru: 'семья', pos: 'noun' },
  { es: 'father', ru: 'отец', pos: 'noun' },
  { es: 'mother', ru: 'мать', pos: 'noun' },
  { es: 'son', ru: 'сын', pos: 'noun' },
  { es: 'daughter', ru: 'дочь', pos: 'noun' },
  { es: 'brother', ru: 'брат', pos: 'noun' },
  { es: 'sister', ru: 'сестра', pos: 'noun' },
  { es: 'job', ru: 'работа', pos: 'noun' },
  { es: 'school', ru: 'школа', pos: 'noun' },
  { es: 'city', ru: 'город', pos: 'noun' },
  { es: 'country', ru: 'страна', pos: 'noun' },
  { es: 'world', ru: 'мир', pos: 'noun' },
  { es: 'street', ru: 'улица', pos: 'noun' },
  { es: 'car', ru: 'машина', pos: 'noun' },
  { es: 'food', ru: 'еда', pos: 'noun' },
  { es: 'water', ru: 'вода', pos: 'noun' },
  { es: 'bread', ru: 'хлеб', pos: 'noun' },
  { es: 'milk', ru: 'молоко', pos: 'noun' },
  { es: 'coffee', ru: 'кофе', pos: 'noun' },
  { es: 'tea', ru: 'чай', pos: 'noun' },
  { es: 'meat', ru: 'мясо', pos: 'noun' },
  { es: 'money', ru: 'деньги', pos: 'noun' },
  { es: 'shop', ru: 'магазин', pos: 'noun' },
  { es: 'book', ru: 'книга', pos: 'noun' },
  { es: 'table', ru: 'стол', pos: 'noun' },
  { es: 'chair', ru: 'стул', pos: 'noun' },
  { es: 'door', ru: 'дверь', pos: 'noun' },
  { es: 'window', ru: 'окно', pos: 'noun' },
  { es: 'bed', ru: 'кровать', pos: 'noun' },
  { es: 'room', ru: 'комната', pos: 'noun' },
  { es: 'phone', ru: 'телефон', pos: 'noun' },
  { es: 'clothes', ru: 'одежда', pos: 'noun' },
  { es: 'head', ru: 'голова', pos: 'noun' },
  { es: 'hand', ru: 'рука', pos: 'noun' },
  { es: 'foot', ru: 'нога (ступня)', pos: 'noun' },
  { es: 'eye', ru: 'глаз', pos: 'noun' },
  { es: 'heart', ru: 'сердце', pos: 'noun' },
  { es: 'sun', ru: 'солнце', pos: 'noun' },
  { es: 'sea', ru: 'море', pos: 'noun' },
  { es: 'tree', ru: 'дерево', pos: 'noun' },
  { es: 'flower', ru: 'цветок', pos: 'noun' },
  { es: 'dog', ru: 'собака', pos: 'noun' },
  { es: 'cat', ru: 'кот, кошка', pos: 'noun' },
  { es: 'name', ru: 'имя', pos: 'noun' },
  { es: 'question', ru: 'вопрос', pos: 'noun' },
  { es: 'answer', ru: 'ответ', pos: 'noun' },
  { es: 'word', ru: 'слово', pos: 'noun' },
  { es: 'language', ru: 'язык (речь)', pos: 'noun' },
  { es: 'thing', ru: 'вещь', pos: 'noun' },
  { es: 'life', ru: 'жизнь', pos: 'noun' },
  { es: 'health', ru: 'здоровье', pos: 'noun' },
  { es: 'doctor', ru: 'врач', pos: 'noun' },
  { es: 'people', ru: 'люди', pos: 'noun' },
  { es: 'music', ru: 'музыка', pos: 'noun' },
  { es: 'movie', ru: 'фильм', pos: 'noun' },
  { es: 'rain', ru: 'дождь', pos: 'noun' },
  // Прилагательные
  { es: 'good', ru: 'хороший', pos: 'adj' },
  { es: 'bad', ru: 'плохой', pos: 'adj' },
  { es: 'big', ru: 'большой', pos: 'adj' },
  { es: 'small', ru: 'маленький', pos: 'adj' },
  { es: 'new', ru: 'новый', pos: 'adj' },
  { es: 'old', ru: 'старый', pos: 'adj' },
  { es: 'young', ru: 'молодой', pos: 'adj' },
  { es: 'beautiful', ru: 'красивый', pos: 'adj' },
  { es: 'tall', ru: 'высокий', pos: 'adj' },
  { es: 'long', ru: 'длинный', pos: 'adj' },
  { es: 'short', ru: 'короткий; низкий', pos: 'adj' },
  { es: 'hot', ru: 'горячий, жаркий', pos: 'adj' },
  { es: 'cold', ru: 'холодный', pos: 'adj' },
  { es: 'easy', ru: 'лёгкий, простой', pos: 'adj' },
  { es: 'difficult', ru: 'трудный', pos: 'adj' },
  { es: 'fast', ru: 'быстрый', pos: 'adj' },
  { es: 'slow', ru: 'медленный', pos: 'adj' },
  { es: 'happy', ru: 'счастливый', pos: 'adj' },
  { es: 'sad', ru: 'грустный', pos: 'adj' },
  { es: 'expensive', ru: 'дорогой', pos: 'adj' },
  { es: 'cheap', ru: 'дешёвый', pos: 'adj' },
  { es: 'important', ru: 'важный', pos: 'adj' },
  { es: 'interesting', ru: 'интересный', pos: 'adj' },
  // Наречия
  { es: 'today', ru: 'сегодня', pos: 'adv' },
  { es: 'yesterday', ru: 'вчера', pos: 'adv' },
  { es: 'tomorrow', ru: 'завтра', pos: 'adv' },
  { es: 'now', ru: 'сейчас', pos: 'adv' },
  { es: 'always', ru: 'всегда', pos: 'adv' },
  { es: 'never', ru: 'никогда', pos: 'adv' },
  { es: 'here', ru: 'здесь', pos: 'adv' },
  { es: 'there', ru: 'там', pos: 'adv' },
  { es: 'well', ru: 'хорошо', pos: 'adv' },
  { es: 'very', ru: 'очень', pos: 'adv' },
  { es: 'much', ru: 'много', pos: 'adv' },
  { es: 'little', ru: 'мало; маленький', pos: 'adv' },
  { es: 'also', ru: 'тоже', pos: 'adv' },
  { es: 'already', ru: 'уже', pos: 'adv' },
  { es: 'still', ru: 'ещё, всё ещё', pos: 'adv' },
];

const FOOD_WORDS: SeedWord[] = [
  { es: 'desayuno', ru: 'завтрак', pos: 'noun' },
  { es: 'almuerzo', ru: 'обед', pos: 'noun' },
  { es: 'cena', ru: 'ужин', pos: 'noun' },
  { es: 'restaurante', ru: 'ресторан', pos: 'noun' },
  { es: 'camarero', ru: 'официант', pos: 'noun' },
  { es: 'menú', ru: 'меню', pos: 'noun' },
  { es: 'cuenta', ru: 'счёт', pos: 'noun' },
  { es: 'propina', ru: 'чаевые', pos: 'noun' },
  { es: 'arroz', ru: 'рис', pos: 'noun' },
  { es: 'huevo', ru: 'яйцо', pos: 'noun' },
  { es: 'queso', ru: 'сыр', pos: 'noun' },
  { es: 'pollo', ru: 'курица', pos: 'noun' },
  { es: 'sopa', ru: 'суп', pos: 'noun' },
  { es: 'ensalada', ru: 'салат', pos: 'noun' },
  { es: 'postre', ru: 'десерт', pos: 'noun' },
  { es: 'helado', ru: 'мороженое', pos: 'noun' },
  { es: 'pastel', ru: 'торт, пирог', pos: 'noun' },
  { es: 'azúcar', ru: 'сахар', pos: 'noun' },
  { es: 'sal', ru: 'соль', pos: 'noun' },
  { es: 'pimienta', ru: 'перец', pos: 'noun' },
  { es: 'aceite', ru: 'масло (растительное)', pos: 'noun' },
  { es: 'mantequilla', ru: 'сливочное масло', pos: 'noun' },
  { es: 'cuchara', ru: 'ложка', pos: 'noun' },
  { es: 'tenedor', ru: 'вилка', pos: 'noun' },
  { es: 'cuchillo', ru: 'нож', pos: 'noun' },
  { es: 'plato', ru: 'тарелка, блюдо', pos: 'noun' },
  { es: 'vaso', ru: 'стакан', pos: 'noun' },
  { es: 'taza', ru: 'чашка', pos: 'noun' },
  { es: 'botella', ru: 'бутылка', pos: 'noun' },
  { es: 'jugo', ru: 'сок', pos: 'noun' },
  { es: 'cerveza', ru: 'пиво', pos: 'noun' },
  { es: 'naranja', ru: 'апельсин', pos: 'noun' },
  { es: 'plátano', ru: 'банан', pos: 'noun' },
  { es: 'uva', ru: 'виноград', pos: 'noun' },
  { es: 'fresa', ru: 'клубника', pos: 'noun' },
  { es: 'tomate', ru: 'помидор', pos: 'noun' },
  { es: 'patata', ru: 'картофель', pos: 'noun' },
  { es: 'cebolla', ru: 'лук', pos: 'noun' },
  { es: 'ajo', ru: 'чеснок', pos: 'noun' },
  { es: 'pedir', ru: 'заказывать, просить', pos: 'verb' },
  { es: 'probar', ru: 'пробовать', pos: 'verb' },
  { es: 'desayunar', ru: 'завтракать', pos: 'verb' },
  { es: 'sabroso', ru: 'вкусный', pos: 'adj' },
  { es: 'dulce', ru: 'сладкий', pos: 'adj' },
  { es: 'salado', ru: 'солёный', pos: 'adj' },
  { es: 'picante', ru: 'острый', pos: 'adj' },
  { es: 'fresco', ru: 'свежий', pos: 'adj' },
  { es: 'tengo hambre', ru: 'я голоден', pos: 'phrase' },
  { es: 'tengo sed', ru: 'я хочу пить', pos: 'phrase' },
  { es: 'la cuenta, por favor', ru: 'счёт, пожалуйста', pos: 'phrase' },
];

const TRAVEL_WORDS: SeedWord[] = [
  { es: 'viaje', ru: 'путешествие', pos: 'noun' },
  { es: 'aeropuerto', ru: 'аэропорт', pos: 'noun' },
  { es: 'vuelo', ru: 'рейс, полёт', pos: 'noun' },
  { es: 'estación', ru: 'вокзал, станция', pos: 'noun' },
  { es: 'billete', ru: 'билет', pos: 'noun' },
  { es: 'pasaporte', ru: 'паспорт', pos: 'noun' },
  { es: 'maleta', ru: 'чемодан', pos: 'noun' },
  { es: 'equipaje', ru: 'багаж', pos: 'noun' },
  { es: 'hotel', ru: 'отель', pos: 'noun' },
  { es: 'reserva', ru: 'бронь', pos: 'noun' },
  { es: 'llave', ru: 'ключ', pos: 'noun' },
  { es: 'mapa', ru: 'карта (географическая)', pos: 'noun' },
  { es: 'turista', ru: 'турист', pos: 'noun' },
  { es: 'guía', ru: 'гид; путеводитель', pos: 'noun' },
  { es: 'museo', ru: 'музей', pos: 'noun' },
  { es: 'iglesia', ru: 'церковь', pos: 'noun' },
  { es: 'plaza', ru: 'площадь', pos: 'noun' },
  { es: 'puente', ru: 'мост', pos: 'noun' },
  { es: 'centro', ru: 'центр', pos: 'noun' },
  { es: 'taxi', ru: 'такси', pos: 'noun' },
  { es: 'metro', ru: 'метро', pos: 'noun' },
  { es: 'autobús', ru: 'автобус', pos: 'noun' },
  { es: 'parada', ru: 'остановка', pos: 'noun' },
  { es: 'salida', ru: 'выход; отправление', pos: 'noun' },
  { es: 'entrada', ru: 'вход; билет на вход', pos: 'noun' },
  { es: 'frontera', ru: 'граница', pos: 'noun' },
  { es: 'aduana', ru: 'таможня', pos: 'noun' },
  { es: 'cámara', ru: 'фотоаппарат', pos: 'noun' },
  { es: 'foto', ru: 'фотография', pos: 'noun' },
  { es: 'recuerdo', ru: 'сувенир; воспоминание', pos: 'noun' },
  { es: 'norte', ru: 'север', pos: 'noun' },
  { es: 'sur', ru: 'юг', pos: 'noun' },
  { es: 'este', ru: 'восток', pos: 'noun' },
  { es: 'oeste', ru: 'запад', pos: 'noun' },
  { es: 'derecha', ru: 'право, направо', pos: 'other' },
  { es: 'izquierda', ru: 'лево, налево', pos: 'other' },
  { es: 'recto', ru: 'прямо', pos: 'adv' },
  { es: 'cerca', ru: 'близко', pos: 'adv' },
  { es: 'lejos', ru: 'далеко', pos: 'adv' },
  { es: 'reservar', ru: 'бронировать', pos: 'verb' },
  { es: 'visitar', ru: 'посещать', pos: 'verb' },
  { es: 'perderse', ru: 'заблудиться', pos: 'verb' },
  { es: '¿dónde está...?', ru: 'где находится...?', pos: 'phrase' },
  { es: '¿cuánto cuesta?', ru: 'сколько стоит?', pos: 'phrase' },
  { es: 'no entiendo', ru: 'я не понимаю', pos: 'phrase' },
  { es: '¿habla usted inglés?', ru: 'вы говорите по-английски?', pos: 'phrase' },
];

const NUMBERS_TIME_WORDS: SeedWord[] = [
  { es: 'cero', ru: 'ноль', pos: 'other' },
  { es: 'uno', ru: 'один', pos: 'other' },
  { es: 'dos', ru: 'два', pos: 'other' },
  { es: 'tres', ru: 'три', pos: 'other' },
  { es: 'cuatro', ru: 'четыре', pos: 'other' },
  { es: 'cinco', ru: 'пять', pos: 'other' },
  { es: 'seis', ru: 'шесть', pos: 'other' },
  { es: 'siete', ru: 'семь', pos: 'other' },
  { es: 'ocho', ru: 'восемь', pos: 'other' },
  { es: 'nueve', ru: 'девять', pos: 'other' },
  { es: 'diez', ru: 'десять', pos: 'other' },
  { es: 'veinte', ru: 'двадцать', pos: 'other' },
  { es: 'treinta', ru: 'тридцать', pos: 'other' },
  { es: 'cuarenta', ru: 'сорок', pos: 'other' },
  { es: 'cincuenta', ru: 'пятьдесят', pos: 'other' },
  { es: 'cien', ru: 'сто', pos: 'other' },
  { es: 'mil', ru: 'тысяча', pos: 'other' },
  { es: 'primero', ru: 'первый', pos: 'adj' },
  { es: 'último', ru: 'последний', pos: 'adj' },
  { es: 'lunes', ru: 'понедельник', pos: 'noun' },
  { es: 'martes', ru: 'вторник', pos: 'noun' },
  { es: 'miércoles', ru: 'среда', pos: 'noun' },
  { es: 'jueves', ru: 'четверг', pos: 'noun' },
  { es: 'viernes', ru: 'пятница', pos: 'noun' },
  { es: 'sábado', ru: 'суббота', pos: 'noun' },
  { es: 'domingo', ru: 'воскресенье', pos: 'noun' },
  { es: 'fin de semana', ru: 'выходные', pos: 'phrase' },
  { es: 'primavera', ru: 'весна', pos: 'noun' },
  { es: 'verano', ru: 'лето', pos: 'noun' },
  { es: 'otoño', ru: 'осень', pos: 'noun' },
  { es: 'invierno', ru: 'зима', pos: 'noun' },
  { es: 'minuto', ru: 'минута', pos: 'noun' },
  { es: 'segundo', ru: 'секунда; второй', pos: 'noun' },
  { es: 'reloj', ru: 'часы', pos: 'noun' },
  { es: 'fecha', ru: 'дата', pos: 'noun' },
  { es: 'cumpleaños', ru: 'день рождения', pos: 'noun' },
  { es: 'temprano', ru: 'рано', pos: 'adv' },
  { es: 'tarde', ru: 'поздно; вечер', pos: 'adv' },
  { es: '¿qué hora es?', ru: 'который час?', pos: 'phrase' },
];

export const WORD_PACKS: WordPack[] = [
  {
    id: 'base200',
    name: 'Базовый словарь',
    description: 'Испанский: 200 самых нужных слов',
    emoji: '📗',
    language: 'es',
    words: SEED_WORDS,
  },
  {
    id: 'en-base',
    name: 'Английский: базовый',
    description: 'Английский: базовые слова для старта',
    emoji: '📘',
    language: 'en',
    words: ENGLISH_BASE_WORDS,
  },
  {
    id: 'food',
    name: 'Еда и ресторан',
    description: 'Испанский: продукты, посуда и фразы в кафе',
    emoji: '🍽️',
    language: 'es',
    words: FOOD_WORDS,
  },
  {
    id: 'travel',
    name: 'Путешествия',
    description: 'Испанский: транспорт, отель и фразы туриста',
    emoji: '✈️',
    language: 'es',
    words: TRAVEL_WORDS,
  },
  {
    id: 'numbers',
    name: 'Числа и время',
    description: 'Испанский: числа, дни недели и времена года',
    emoji: '🕐',
    language: 'es',
    words: NUMBERS_TIME_WORDS,
  },
];
