import type { PartOfSpeech } from '@/types';

export interface SeedWord {
  es: string;
  ru: string;
  pos: PartOfSpeech;
}

// Базовый словарь: 200 самых нужных испанских слов с переводом на русский
export const SEED_WORDS: SeedWord[] = [
  // --- Приветствия и фразы ---
  { es: 'hola', ru: 'привет', pos: 'phrase' },
  { es: 'adiós', ru: 'до свидания', pos: 'phrase' },
  { es: 'buenos días', ru: 'доброе утро', pos: 'phrase' },
  { es: 'buenas tardes', ru: 'добрый день', pos: 'phrase' },
  { es: 'buenas noches', ru: 'доброй ночи', pos: 'phrase' },
  { es: 'por favor', ru: 'пожалуйста', pos: 'phrase' },
  { es: 'gracias', ru: 'спасибо', pos: 'phrase' },
  { es: 'de nada', ru: 'не за что', pos: 'phrase' },
  { es: 'lo siento', ru: 'извините, мне жаль', pos: 'phrase' },
  { es: '¿cómo estás?', ru: 'как дела?', pos: 'phrase' },
  { es: 'mucho gusto', ru: 'очень приятно', pos: 'phrase' },
  { es: 'hasta luego', ru: 'до встречи', pos: 'phrase' },

  // --- Базовые слова ---
  { es: 'sí', ru: 'да', pos: 'other' },
  { es: 'no', ru: 'нет', pos: 'other' },
  { es: 'yo', ru: 'я', pos: 'other' },
  { es: 'tú', ru: 'ты', pos: 'other' },
  { es: 'él', ru: 'он', pos: 'other' },
  { es: 'ella', ru: 'она', pos: 'other' },
  { es: 'nosotros', ru: 'мы', pos: 'other' },
  { es: 'ellos', ru: 'они', pos: 'other' },
  { es: 'usted', ru: 'Вы (вежливо)', pos: 'other' },
  { es: 'esto', ru: 'это', pos: 'other' },
  { es: 'qué', ru: 'что', pos: 'other' },
  { es: 'quién', ru: 'кто', pos: 'other' },
  { es: 'dónde', ru: 'где', pos: 'other' },
  { es: 'cuándo', ru: 'когда', pos: 'other' },
  { es: 'por qué', ru: 'почему', pos: 'other' },
  { es: 'cómo', ru: 'как', pos: 'other' },
  { es: 'cuánto', ru: 'сколько', pos: 'other' },
  { es: 'y', ru: 'и', pos: 'other' },
  { es: 'o', ru: 'или', pos: 'other' },
  { es: 'pero', ru: 'но', pos: 'other' },
  { es: 'porque', ru: 'потому что', pos: 'other' },
  { es: 'con', ru: 'с (кем-то, чем-то)', pos: 'other' },
  { es: 'sin', ru: 'без', pos: 'other' },
  { es: 'para', ru: 'для', pos: 'other' },
  { es: 'en', ru: 'в, на', pos: 'other' },
  { es: 'de', ru: 'из, от', pos: 'other' },

  // --- Глаголы ---
  { es: 'ser', ru: 'быть (постоянное)', pos: 'verb' },
  { es: 'estar', ru: 'быть, находиться', pos: 'verb' },
  { es: 'tener', ru: 'иметь', pos: 'verb' },
  { es: 'hacer', ru: 'делать', pos: 'verb' },
  { es: 'ir', ru: 'идти, ехать', pos: 'verb' },
  { es: 'venir', ru: 'приходить', pos: 'verb' },
  { es: 'ver', ru: 'видеть', pos: 'verb' },
  { es: 'dar', ru: 'давать', pos: 'verb' },
  { es: 'saber', ru: 'знать (факты)', pos: 'verb' },
  { es: 'conocer', ru: 'знать, быть знакомым', pos: 'verb' },
  { es: 'querer', ru: 'хотеть, любить', pos: 'verb' },
  { es: 'poder', ru: 'мочь', pos: 'verb' },
  { es: 'decir', ru: 'говорить, сказать', pos: 'verb' },
  { es: 'hablar', ru: 'разговаривать', pos: 'verb' },
  { es: 'comer', ru: 'есть, кушать', pos: 'verb' },
  { es: 'beber', ru: 'пить', pos: 'verb' },
  { es: 'vivir', ru: 'жить', pos: 'verb' },
  { es: 'trabajar', ru: 'работать', pos: 'verb' },
  { es: 'estudiar', ru: 'учиться', pos: 'verb' },
  { es: 'aprender', ru: 'изучать, учить', pos: 'verb' },
  { es: 'leer', ru: 'читать', pos: 'verb' },
  { es: 'escribir', ru: 'писать', pos: 'verb' },
  { es: 'escuchar', ru: 'слушать', pos: 'verb' },
  { es: 'mirar', ru: 'смотреть', pos: 'verb' },
  { es: 'buscar', ru: 'искать', pos: 'verb' },
  { es: 'encontrar', ru: 'находить', pos: 'verb' },
  { es: 'comprar', ru: 'покупать', pos: 'verb' },
  { es: 'vender', ru: 'продавать', pos: 'verb' },
  { es: 'pagar', ru: 'платить', pos: 'verb' },
  { es: 'abrir', ru: 'открывать', pos: 'verb' },
  { es: 'cerrar', ru: 'закрывать', pos: 'verb' },
  { es: 'empezar', ru: 'начинать', pos: 'verb' },
  { es: 'terminar', ru: 'заканчивать', pos: 'verb' },
  { es: 'entender', ru: 'понимать', pos: 'verb' },
  { es: 'pensar', ru: 'думать', pos: 'verb' },
  { es: 'creer', ru: 'верить, считать', pos: 'verb' },
  { es: 'recordar', ru: 'помнить, вспоминать', pos: 'verb' },
  { es: 'dormir', ru: 'спать', pos: 'verb' },
  { es: 'jugar', ru: 'играть', pos: 'verb' },
  { es: 'ayudar', ru: 'помогать', pos: 'verb' },
  { es: 'necesitar', ru: 'нуждаться', pos: 'verb' },
  { es: 'llamar', ru: 'звать, звонить', pos: 'verb' },
  { es: 'llegar', ru: 'прибывать, приходить', pos: 'verb' },
  { es: 'salir', ru: 'выходить', pos: 'verb' },
  { es: 'entrar', ru: 'входить', pos: 'verb' },
  { es: 'volver', ru: 'возвращаться', pos: 'verb' },
  { es: 'esperar', ru: 'ждать, надеяться', pos: 'verb' },
  { es: 'gustar', ru: 'нравиться', pos: 'verb' },
  { es: 'llevar', ru: 'носить, относить', pos: 'verb' },
  { es: 'poner', ru: 'класть, ставить', pos: 'verb' },
  { es: 'tomar', ru: 'брать, пить', pos: 'verb' },

  // --- Существительные ---
  { es: 'casa', ru: 'дом', pos: 'noun' },
  { es: 'tiempo', ru: 'время; погода', pos: 'noun' },
  { es: 'día', ru: 'день', pos: 'noun' },
  { es: 'noche', ru: 'ночь', pos: 'noun' },
  { es: 'semana', ru: 'неделя', pos: 'noun' },
  { es: 'año', ru: 'год', pos: 'noun' },
  { es: 'hombre', ru: 'мужчина, человек', pos: 'noun' },
  { es: 'mujer', ru: 'женщина', pos: 'noun' },
  { es: 'niño', ru: 'ребёнок, мальчик', pos: 'noun' },
  { es: 'amigo', ru: 'друг', pos: 'noun' },
  { es: 'familia', ru: 'семья', pos: 'noun' },
  { es: 'padre', ru: 'отец', pos: 'noun' },
  { es: 'madre', ru: 'мать', pos: 'noun' },
  { es: 'hijo', ru: 'сын', pos: 'noun' },
  { es: 'hermano', ru: 'брат', pos: 'noun' },
  { es: 'trabajo', ru: 'работа', pos: 'noun' },
  { es: 'escuela', ru: 'школа', pos: 'noun' },
  { es: 'ciudad', ru: 'город', pos: 'noun' },
  { es: 'país', ru: 'страна', pos: 'noun' },
  { es: 'mundo', ru: 'мир', pos: 'noun' },
  { es: 'calle', ru: 'улица', pos: 'noun' },
  { es: 'coche', ru: 'машина, автомобиль', pos: 'noun' },
  { es: 'comida', ru: 'еда', pos: 'noun' },
  { es: 'agua', ru: 'вода', pos: 'noun' },
  { es: 'pan', ru: 'хлеб', pos: 'noun' },
  { es: 'leche', ru: 'молоко', pos: 'noun' },
  { es: 'café', ru: 'кофе', pos: 'noun' },
  { es: 'carne', ru: 'мясо', pos: 'noun' },
  { es: 'dinero', ru: 'деньги', pos: 'noun' },
  { es: 'tienda', ru: 'магазин', pos: 'noun' },
  { es: 'libro', ru: 'книга', pos: 'noun' },
  { es: 'mesa', ru: 'стол', pos: 'noun' },
  { es: 'puerta', ru: 'дверь', pos: 'noun' },
  { es: 'cama', ru: 'кровать', pos: 'noun' },
  { es: 'baño', ru: 'ванная, туалет', pos: 'noun' },
  { es: 'habitación', ru: 'комната', pos: 'noun' },
  { es: 'teléfono', ru: 'телефон', pos: 'noun' },
  { es: 'ropa', ru: 'одежда', pos: 'noun' },
  { es: 'cabeza', ru: 'голова', pos: 'noun' },
  { es: 'mano', ru: 'рука (кисть)', pos: 'noun' },
  { es: 'pie', ru: 'нога (ступня)', pos: 'noun' },
  { es: 'ojo', ru: 'глаз', pos: 'noun' },
  { es: 'corazón', ru: 'сердце', pos: 'noun' },
  { es: 'sol', ru: 'солнце', pos: 'noun' },
  { es: 'mar', ru: 'море', pos: 'noun' },
  { es: 'playa', ru: 'пляж', pos: 'noun' },
  { es: 'montaña', ru: 'гора', pos: 'noun' },
  { es: 'árbol', ru: 'дерево', pos: 'noun' },
  { es: 'flor', ru: 'цветок', pos: 'noun' },
  { es: 'perro', ru: 'собака', pos: 'noun' },
  { es: 'gato', ru: 'кот, кошка', pos: 'noun' },
  { es: 'nombre', ru: 'имя', pos: 'noun' },
  { es: 'pregunta', ru: 'вопрос', pos: 'noun' },
  { es: 'respuesta', ru: 'ответ', pos: 'noun' },
  { es: 'palabra', ru: 'слово', pos: 'noun' },
  { es: 'idioma', ru: 'язык (речь)', pos: 'noun' },
  { es: 'cosa', ru: 'вещь', pos: 'noun' },
  { es: 'vida', ru: 'жизнь', pos: 'noun' },
  { es: 'amor', ru: 'любовь', pos: 'noun' },
  { es: 'salud', ru: 'здоровье', pos: 'noun' },
  { es: 'médico', ru: 'врач', pos: 'noun' },
  { es: 'gente', ru: 'люди', pos: 'noun' },
  { es: 'fiesta', ru: 'праздник, вечеринка', pos: 'noun' },
  { es: 'música', ru: 'музыка', pos: 'noun' },
  { es: 'película', ru: 'фильм', pos: 'noun' },
  { es: 'viaje', ru: 'путешествие', pos: 'noun' },
  { es: 'lluvia', ru: 'дождь', pos: 'noun' },

  // --- Прилагательные ---
  { es: 'bueno', ru: 'хороший', pos: 'adj' },
  { es: 'malo', ru: 'плохой', pos: 'adj' },
  { es: 'grande', ru: 'большой', pos: 'adj' },
  { es: 'pequeño', ru: 'маленький', pos: 'adj' },
  { es: 'nuevo', ru: 'новый', pos: 'adj' },
  { es: 'viejo', ru: 'старый', pos: 'adj' },
  { es: 'joven', ru: 'молодой', pos: 'adj' },
  { es: 'bonito', ru: 'красивый', pos: 'adj' },
  { es: 'alto', ru: 'высокий', pos: 'adj' },
  { es: 'bajo', ru: 'низкий', pos: 'adj' },
  { es: 'largo', ru: 'длинный', pos: 'adj' },
  { es: 'corto', ru: 'короткий', pos: 'adj' },
  { es: 'caliente', ru: 'горячий', pos: 'adj' },
  { es: 'frío', ru: 'холодный', pos: 'adj' },
  { es: 'fácil', ru: 'лёгкий, простой', pos: 'adj' },
  { es: 'difícil', ru: 'трудный', pos: 'adj' },
  { es: 'rápido', ru: 'быстрый', pos: 'adj' },
  { es: 'lento', ru: 'медленный', pos: 'adj' },
  { es: 'feliz', ru: 'счастливый', pos: 'adj' },
  { es: 'triste', ru: 'грустный', pos: 'adj' },
  { es: 'cansado', ru: 'уставший', pos: 'adj' },
  { es: 'caro', ru: 'дорогой', pos: 'adj' },
  { es: 'barato', ru: 'дешёвый', pos: 'adj' },
  { es: 'rico', ru: 'богатый; вкусный', pos: 'adj' },
  { es: 'importante', ru: 'важный', pos: 'adj' },
  { es: 'interesante', ru: 'интересный', pos: 'adj' },

  // --- Наречия ---
  { es: 'hoy', ru: 'сегодня', pos: 'adv' },
  { es: 'ayer', ru: 'вчера', pos: 'adv' },
  { es: 'mañana', ru: 'завтра; утро', pos: 'adv' },
  { es: 'ahora', ru: 'сейчас', pos: 'adv' },
  { es: 'siempre', ru: 'всегда', pos: 'adv' },
  { es: 'nunca', ru: 'никогда', pos: 'adv' },
  { es: 'aquí', ru: 'здесь', pos: 'adv' },
  { es: 'allí', ru: 'там', pos: 'adv' },
  { es: 'bien', ru: 'хорошо', pos: 'adv' },
  { es: 'mal', ru: 'плохо', pos: 'adv' },
  { es: 'mucho', ru: 'много', pos: 'adv' },
  { es: 'poco', ru: 'мало', pos: 'adv' },
  { es: 'también', ru: 'тоже', pos: 'adv' },
  { es: 'muy', ru: 'очень', pos: 'adv' },
  { es: 'ya', ru: 'уже', pos: 'adv' },
  { es: 'todavía', ru: 'ещё, всё ещё', pos: 'adv' },
  { es: 'después', ru: 'потом, после', pos: 'adv' },
  { es: 'antes', ru: 'раньше, до', pos: 'adv' },
];
